### ISSUE TITLE
iObserve: No scroll option for long object lists 

### ISSUE THREAD

**Issue by beckysteele** [arcsecond-io/public-issues#45]
**As a user, I would like to be able to scroll in the Objects section when my list of objects exceeds the length of the page.**

**Current State**: the user cannot scroll through a long list or arrow up/down to show the rest of the list. This seems to be the case regardless of screen size.

**Future State**: the user can scroll in this panel, allowing them to select individual objects or shift-select multiple adjacent objects.

**Temp fix**: a user temporarily address this problem by creating multiple folders and splitting their objects amongst them, but this is not ideal.

I will email a screen recording of this issue. Github doesn't support .mov format as attachments.

**Comment by onekiloparsec** [comment]
I was away from my keyboard last night, and couldn't thank you for the quality of these bug reports. Thanks, really. 

As for the scroll, it's definitely a bug. I am struggling with CSS a bit... Will work on it asap.

**Comment by onekiloparsec** [comment]
Fixed and deployed. I close for now, but feel free to reopen if this not ok for you.
