### ISSUE TITLE
iObserve: Feature Request: ctrl-click to select non-adjacent objects

### ISSUE THREAD

**Issue by beckysteele** [arcsecond-io/public-issues#46]
**As a user, I would like to be able to ctrl-click to select non-adjacent objects.** 

**Current State**: the user can shift-click to select adjacent objects, but cannot select multiple objects at one time. This prevents the user from seeing the desired combination of objects in the visibility viewer.

**Future State**: the user can ctrl-click non-adjacent objects to display any combination of objects in the visibility viewer.

**Comment by onekiloparsec** [comment]
It used to work, with the meta key. But the "meta key" is different depending on your platform (macOS, windows...).... 

Just tested right now, and it doesn't work. Damn.

**Comment by onekiloparsec** [comment]
Source of bug found: https://github.com/holiber/sl-vue-tree/pull/22 

We don't need to wait for the PR merging. The issue will be fixed on next deploy.

**Comment by onekiloparsec** [comment]
Fixed and deployed. I close for now, but feel free to reopen if this not ok for you.
