### ISSUE TITLE
iObserve: Feature Request: Upload list of multiple objects

### ISSUE THREAD

**Issue by beckysteele** [arcsecond-io/public-issues#47]
**As a user, I would like to be able to upload a file in a common delimiter format (.tbl, .csv, .xls, .xlsx) with a list of objects organized by Name, RA, and Dec, and have that import into my list of objects either as individual objects or inside a new folder.**

**Current State**: the user has to manually add objects by RA/Dec if those objects are not easily identified in SIMBAD. This is tedious and time consuming.

**Future State**: the user can upload a file, iObserve will parse the file with the appropriate delimiter, and populate those objects into the Objects list.

**Comment by onekiloparsec** [comment]
I will work on this probably in the coming days. Do you have an example file to share ? It would help starting. Thanks.

**Comment by onekiloparsec** [comment]
This is very very late, but there were too numerous things to do. Since last November I am focused on delivering a whole new and tested and reliable iObserve on the web. It implies a few auxiliary things that take a lot more time than expected, but I'm an on it actively. ETA: before summer.

**Comment by onekiloparsec** [comment]
Hello Becky. It has been a wayyyyy too long road, I am sorry. The webapp underwent very strong change in its foundations, and it is now much more tested, and well organised. 

This all said, the proposed new feature is now available, as well as the import of Exoplanets into iObserve on the web. 

Feel free to re-open the issue if this doesn't fit your needs.
