### ISSUE TITLE
iObserve: Feature Request: Set preferences for RA format

### ISSUE THREAD

**Issue by beckysteele** [arcsecond-io/public-issues#48]
**As a user, I'd like the ability to set my preferred format for right ascension.**

**Current State**: when entering a manual object, the user has to uncheck the "Right Ascension in Hours:" box every time if their RA is in degrees (which is the case for a lot of astronomers who work with extragalactic data). 

**Future State**: the user can set preferences for RA format in Degrees.

**Temporary Fix**: because there is no way to edit objects after manually creating them, if the user enters RA/Dec in degrees and forgets to uncheck the box, they can delete the object entirely and create a new object with the box unchecked.

**Comment by onekiloparsec** [comment]
Improved and deployed. I close for now, but feel free to reopen if this not ok for you.
