### ISSUE TITLE
iObserve: Cannot deselect active folder (to create/view other folders)

### ISSUE THREAD

**Issue by beckysteele** [arcsecond-io/public-issues#49]
**As a user, I'd like to be able to deselect the active folder in my Objects list so that I can either create a new folder or view objects in another existing folder.**

**Current State**: the user cannot deselect the active folder, which means that new folders will be created in the active folder only. I'm emailing a screen recording for this issue, because on the third try of creating a folder outside of the active folder, it did do it. However, when creating a third folder, it was embedded inside the most recent active folder.

**Future State**: the user can click elsewhere or hit Esc to deselect active folders and create new/view existing folders.

**Temporary Fix**: persistence? I'm not sure why it worked on the third try but not the first two (see recording).

**Comment by onekiloparsec** [comment]
I received a backend error report that can be related to this (revealing an issue on a node creation – the second folder ?). Will check asap.

**Comment by onekiloparsec** [comment]
This is a partial fix. Hitting `Esc` not correctly deselect everything.

**Comment by onekiloparsec** [comment]
A complete fix is now deployed. You can hit `esc` or click in a empty area in the left-hand panel.
