### ISSUE TITLE
Calendar display is strange

### ISSUE THREAD

**Issue by mdcleir** [arcsecond-io/public-issues#60]
The calendar display is strange. The dates and days do not match. Today is Tuesday 25th, not Sunday or Saturday. I think the problem is that there are 6 days per line:
![screen shot 2019-02-26 at 13 35 00](https://user-images.githubusercontent.com/45097951/53413077-5b096f00-39cb-11e9-9a82-eb3e479df04c.png)

**Comment by onekiloparsec** [comment]
Thanks for the bug report. Indeed, there is a mismatch due to the misplacement of that right-facing arrow.

**Comment by onekiloparsec** [comment]
Fixed and deployed.
